 const ProductData = [
    {
      id: 1,
      name: "Teddy Bear",
      price: 19.99,
      description: "Soft and cuddly teddy bear for children of all ages.",
      image: "/image/taddybear.webp",
      category: "Baby",
      sales: true,
      ageGroup: "0-3 Years",
    },
    {
      id: 2,
      name: "LEGO Classic Set",
      price: 29.99,
      description: "Creative building blocks for endless imagination.",
      image: "/image/class.jpg",
      category: "Baby",
      sales: false,
      ageGroup: "4-7 Years",
    },
    {
      id: 3,
      name: "Remote Control Car",
      price: 39.99,
      description: "Fast and fun remote-controlled car for racing enthusiasts.",
      image: "/image/RemoCar.jpg",
      category: "Baby ",
      sales: true,
      ageGroup: "4-7 Years",
    },
    {
      id: 4,
      name: "Barbie Doll",
      price: 2.99,
      description: "Classic Barbie doll with fashionable accessories.",
      image: "/image/BarbieDoll.jpg",
      category: "KIDS",
      sales: true,
      ageGroup: "4-7 Years",
    },
    {
      id: 5,
      name: "Nerf Blaster",
      price: 34.99,
      description: "Foam dart blaster for safe and exciting play.",
      image: "/image/NerfBlaster.jpg",
      category: "Action Toys",
      sales: true,
      ageGroup: "4-7 Years",
    },
    {
      id: 6,
      name: "Play-Doh Set",
      price: 14.99,
      description: "Colorful modeling compound for creative sculpting.",
      image: "/image/PlayDohSet.jpeg",
      category: "Arts & Crafts " ,
      sales: false,
      ageGroup: "4-7 Years",
    },
    {
      id: 7,
      name: "Puzzle Set",
      price: 17.99,
      description: "Challenging jigsaw puzzles for all skill levels.",
      image: "/image/PuzzleSet.jpg",
      category: "Puzzles",
      sales: true,
      ageGroup: "8-12 Years",
    },
    {
      id: 8,
      name: "Hot Wheels Cars",
      price: 9.99,
      description: "Set of die-cast toy cars for racing and collecting.",
      image: "/image/HotWheelsCars.jpg",
      category: "Vehicles",
      sales: false,
      ageGroup: "8-12 Years",
    },
    {
      id: 9,
      name: "Board Game Bundle",
      price: 44.99,
      description: "Collection of classic board games for family fun.",
      image: "/image/Board.jpeg",
      category: "Board Games",
      sales: true,
      ageGroup: "8-12 Years",
    },
    {
      id: 10,
      name: "Toy Kitchen Set",
      price: 59.99,
      description: "Realistic play kitchen for aspiring young chefs.",
      image: "/image/Kitchen.jpeg",
      category: "Pretend Play",
      sales: false,
      ageGroup: "8-12 Years",
    },
    {
      id: 11,
      name: "Rubik's Cube",
      price: 12.99,
      description: "Classic 3D combination puzzle for problem-solving skills.",
      image: "/image/td1.webp",
      category: "Puzzles",
      sales: true,
      ageGroup: "8-12 Years",
    },
      {
        id: 12,
        name: "Toy Train Set",
        price: 49.99,
        description: "Wooden train set with tracks and accessories.",
        image: "/image/Train.jfif",
        category: "Vehicles",
        sales: false,
        ageGroup: "13+ Years",
      },
      {
        id: 13,
        name: "Superhero Action Figure",
        price: 14.99,
        description: "Poseable action figure of popular superhero character.",
        image: "/image/super.webp",
        category: "Action Figures",
        sales: true,
        ageGroup: "13+ Years",
      },
      {
        id: 14,
        name: "Science Experiment Kit",
        price: 29.99,
        description: "Educational kit for conducting safe science experiments.",
        image: "/image/science-kit.jfif",
        category: "Educational",
        sales: false,
        ageGroup: "13+ Years",
      },
      {
        id: 15,
        name: "Toy Guitar",
        price: 24.99,
        description: "Miniature guitar for young music enthusiasts.",
        image: "/image/toy-guitar.jfif",
        category: "Musical Instruments",
        sales: true,
        ageGroup: "13+ Years",
      },
      {
        id: 16,
        name: "Dollhouse",
        price: 79.99,
        description: "Multi-level dollhouse with furniture and accessories.",
        image: "/image/dollhouse.jfif",
        category: "Dolls",
        sales: false,
        ageGroup: "13+ Years",
      },
      {
        id: 17,
        name: "Art Easel",
        price: 39.99,
        description: "Double-sided art easel with chalkboard and whiteboard.",
        image: "/image/art-easel.jpg",
        category: "Arts & Crafts",
        sales: true,
        ageGroup: "0-3 Years",
      },
      {
        id: 18,
        name: "Toy Cash Register",
        price: 22.99,
        description: "Interactive cash register for pretend play shopping.",
        image: "/image/cash-register.jfif",
        category: "Pretend Play",
        sales: false,
        ageGroup: "0-3 Years",
      },
      {
        id: 19,
        name: "Dinosaur Figurine Set",
        price: 19.99,
        description: "Collection of realistic dinosaur figurines.",
        image: "/image/dinosaur-set.jfif",
        category: "Animal Toys",
        sales: true,
        ageGroup: "0-3 Years",
      },
      {
        id: 20,
        name: "Toy Doctor Kit",
        price: 18.99,
        description: "Medical play set for aspiring young doctors.",
        image: "/image/doctor-kit.jfif",
        category: "Pretend Play",
        sales: false,
        ageGroup: "0-3 Years",
      },    // {
      {
        id: 21,
        name: "Remote Control Drone",
        price: 69.99,
        description: "Beginner-friendly drone with camera for aerial photography.",
        image: "/image/rc-drone.jpg",
        category: "Remote Control",
        sales: true,
        ageGroup: "0-3 Years",
      },
      {
        id: 22,
        name: "Toy Workbench",
        price: 54.99,
        description: "Realistic workbench with tools for little builders.",
        image: "/image/toy-workbench.jfif",
        category: "Pretend Play",
        sales: false,
        ageGroup: "0-3 Years",
      },
      {
        id: 23,
        name: "Slime Kit",
        price: 15.99,
        description: "DIY slime-making kit with various colors and add-ins.",
        image: "/image/slime-kit.jfif",
        category: "Arts & Crafts",
        sales: true,
        ageGroup: "0-3 Years",
      },
      {
        id: 24,
        name: "Toy Telescope",
        price: 29.99,
        description: "Educational telescope for young astronomers.",
        image: "/image/telescope.jfif",
        category: "Educational",
        sales: false,
        ageGroup: "4-7 Years",
      },
      {
        id: 25,
        name: "Play Tent",
        price: 34.99,
        description: "Pop-up play tent for indoor and outdoor adventures.",
        image: "/image/play-tent.jfif",
        category: "Outdoor Toys",
        sales: true,
        ageGroup: "4-7 Years",
      },
      {
        id: 26,
        name: "Toy Drum Set",
        price: 49.99,
        description: "Junior drum set for budding musicians.",
        image: "/image/drum-set..jfif",
        category: "Musical Instruments",
        sales: false,
        ageGroup: "8-12 Years",
      },
      {
        id: 27,
        name: "Magnetic Building Tiles",
        price: 39.99,
        description: "Colorful magnetic tiles for 3D construction play.",
        image: "/image/magnetic-tiles..jfif",
        category: "Building Toys",
        sales: true,
        ageGroup: "8-12 Years",
      },
      {
        id: 28,
        name: "Toy Laptop",
        price: 27.99,
        description: "Educational toy laptop with learning games and activities.",
        image: "/image/toy-laptop.jfif",
        category: "Educational",
        sales: false,
        ageGroup: "8-12 Years",
      },
      {
        id: 29,
        name: "Bubble Machine",
        price: 19.99,
        description: "Automatic bubble blower for endless bubble fun.",
        image: "/image/bubble-machine.jfif",
        category: "Outdoor Toys",
        sales: true,
        ageGroup: "0-3 Years",
      },
      {
        id: 30,
        name: "Toy Tool Belt",
        price: 16.99,
        description: "Adjustable tool belt with plastic tools for little handymen.",
        image: "/image/tool-belt.jpg",
        category: "Pretend Play",
        sales: false,
        ageGroup: "0-3 Years",
      },    // {
    //   id: 31,
    //   name: "Kinetic Sand Kit",
    //   price: 21.99,
    //   description: "Moldable kinetic sand with shaping tools.",
    //   image: "kinetic-sand.jpg",
    //   category: "Arts & Crafts",
    //   sales: true,
    // },
    // {
    //   id: 32,
    //   name: "Toy Microscope",
    //   price: 32.99,
    //   description: "Beginner microscope set for young scientists.",
    //   image: "microscope.jpg",
    //   category: "Educational",
    //   sales: false,
    // },
    // {
    //   id: 33,
    //   name: "Toy Shopping Cart",
    //   price: 24.99,
    //   description: "Miniature shopping cart for pretend grocery shopping.",
    //   image: "shopping-cart.jpg",
    //   category: "Pretend Play",
    //   sales: true,
    // },
    // {
    //   id: 34,
    //   name: "RC Helicopter",
    //   price: 44.99,
    //   description: "Remote-controlled helicopter for indoor flying fun.",
    //   image: "rc-helicopter.jpg",
    //   category: "Remote Control",
    //   sales: false,
    // },
    // {
    //   id: 35,
    //   name: "Toy Sword and Shield",
    //   price: 19.99,
    //   description: "Foam sword and shield set for safe role-playing.",
    //   image: "sword-shield.jpg",
    //   category: "Dress Up",
    //   sales: true,
    // },
    // {
    //   id: 36,
    //   name: "Toy Vanity Set",
    //   price: 39.99,
    //   description: "Pretend play vanity with mirror and accessories.",
    //   image: "vanity-set.jpg",
    //   category: "Pretend Play",
    //   sales: false,
    // },
    // {
    //   id: 37,
    //   name: "Toy Walkie Talkies",
    //   price: 29.99,
    //   description: "Set of two walkie talkies for outdoor communication play.",
    //   image: "walkie-talkies.jpg",
    //   category: "Outdoor Toys",
    //   sales: true,
    // },
    // {
    //   id: 38,
    //   name: "Toy Fishing Set",
    //   price: 17.99,
    //   description: "Magnetic fishing game with rod and plastic fish.",
    //   image: "fishing-set.jpg",
    //   category: "Outdoor Toys",
    //   sales: false,
    // },
    // {
    //   id: 39,
    //   name: "Toy Vacuum Cleaner",
    //   price: 26.99,
    //   description: "Realistic toy vacuum with sound effects.",
    //   image: "toy-vacuum.jpg",
    //   category: "Pretend Play",
    //   sales: true,
    // },
    // {
    //   id: 40,
    //   name: "Toy Archery Set",
    //   price: 23.99,
    //   description: "Bow and arrow set with target for safe archery practice.",
    //   image: "archery-set.jpg",
    //   category: "Outdoor Toys",
    //   sales: false,
    // },
    // {
    //   id: 41,
    //   name: "Toy Xylophone",
    //   price: 18.99,
    //   description: "Colorful xylophone for early musical education.",
    //   image: "xylophone.jpg",
    //   category: "Musical Instruments",
    //   sales: true,
    // },
    // {
    //   id: 42,
    //   name: "Toy Binoculars",
    //   price: 14.99,
    //   description: "Kid-friendly binoculars for outdoor exploration.",
    //   image: "binoculars.jpg",
    //   category: "Outdoor Toys",
    //   sales: false,
    // },
    // {
    //   id: 43,
    //   name: "Toy Steering Wheel",
    //   price: 22.99,
    //   description: "Interactive steering wheel with sounds for pretend driving.",
    //   image: "steering-wheel.jpg",
    //   category: "Pretend Play",
    //   sales: true,
    // },
    // {
    //   id: 44,
    //   name: "Toy Projector",
    //   price: 29.99,
    //   description: "Simple projector for displaying stories and images.",
    //   image: "toy-projector.jpg",
    //   category: "Educational",
    //   sales: false,
    // },
    // {
    //   id: 45,
    //   name: "Toy Gardening Set",
    //   price: 16.99,
    //   description: "Kid-sized gardening tools and watering
  ]
  export default ProductData;